import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Cine Rental | Learn with Sumit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} dark:bg-body bg-white font-[Sora] dark:text-white text-dark`}
      >
        <Navbar />
        <main className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
          <Sidebar />
          {children}
        </main>
        <Footer />
        <div id="modal-root-content" />
      </body>
    </html>
  );
}
