import "@/app/globals.css";
import { Sora } from "next/font/google";

const sora = Sora({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Cine Rental | Learn with Sumit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} dark:bg-body bg-white font-[Sora] dark:text-white text-dark`}
      >
        {children}
        <div id="modal-root-content" />
      </body>
    </html>
  );
}
